### ISSUE TITLE
AutoTiling Support

### ISSUE THREAD

**Issue by JustSimplyKyle** [outfoxxed/hy3#10]
Conversation stripped from Discord.

> Not changing move logic makes it a lot faster, and an autotiled flag isnt hard to add
Move logic is somewhat complex
But splitting on creation isnt hard

So like an option `hy3:split_on_creation # automatic splitting the created window based on height and width`?
As for the other

**Comment by outfoxxed** [comment]
Added in 22a65c1

**Comment by piotryordanov** [comment]
can i bind a hotkey to change autotiling from true to false, and vise versa?

**Comment by outfoxxed** [comment]
@piotryordanov this should be doable via `hyprctl keyword`
