### ISSUE TITLE
Tab bar visual defects

### ISSUE THREAD

**Issue by postsolar** [outfoxxed/hy3#100]
When I switch to a workspace with tabbed nodes, the tabs strip gets visual defects.
See the video attached, specifically the magenta color tab bar strip in the top-left corner when on workspace 7.
On this recording, the defects disappear themselves after a couple seconds, but when I'm not recording they actually do not disappear at all unless I do something on that workspace (e.g. switch the tab, or focus another node, etc).

https://github.com/outfoxxed/hy3/assets/120750161/f0aa2fd4-817d-474a-ad10-f9a515a15dcf

I've been having it since ~0.37 I think. Currently I'm on Hyprland master (63e3668529f6c06478ec288723d0ba46374c4bc5) and Hy3 master (0177c6fc45ba730c4a6c194ee8ee261ee6d96da4).

This seems to persist with no hy3 config and (almost) no hyprland config, as well as no other plugins.

Seems to be that what the defects look like depends on the animations in place. Disabling animations doesn't prevent them though.

**Comment by elegaanz** [comment]
I have the same (or at least very similar) issue. I am currently on hyprland 0.38.1 and the matching hy3 version, and it didn't happen with previous versions. Also, I'm running Linux 6.8.4 with Nvidia drivers  (the `nvidia` pacakage of ArchLinux on the `550.67-5` version).

https://github.com/outfoxxed/hy3/assets/16254623/85971168-420d-43b5-8d1a-014dad8ca74a

**Comment by zetaPRIME** [comment]
Having the same issue. hyprland 0.38.1, RX 5700, kernel `6.8.4-zen1-1-zen` (as reported by neofetch); corruption only goes away when something forces the tab bar to update (changing tabs, a window title changing)

**Comment by GG2R10** [comment]
Same issue. In my case it just crashes and unloads the plugin using `hyprctl plugin` and the AUR package hy3-git in Arch. When i use it with hyprpm it literally freezes my PC. It's curious because when i have swww with a GIF as background, the bars doesn't has the weird glitches but shows up like at low FPS. I guess it's because, as the others are saying, the frame change of the GIF forces the tabs to update.


https://github.com/outfoxxed/hy3/assets/114362342/f5d80089-9218-4136-99ef-302eb913be08

**Comment by postsolar** [comment]
As a quick workaround, I noticed it doesn't happen (or is unnoticeable) when the workspace switching animation style is set to `fade`

```
animations {
  easeInOutExpo = 0.87, 0, 0.13, 1
  animation = workspaces, 1, 10, easeInOutExpo, fade
}
```

There are possibly some more animations configurations which can alleviate it, I haven't tried them all.

**Comment by Omrigan** [comment]
> bezier = easeInOutExpo, 0.87, 0, 0.13, 1
>   animation = workspaces, 1, 10, easeInOutExpo, fade

Doesn't help me on Hyprland 0.40.0

**Comment by zoli** [comment]
Also having this problem I'm not sure it's rooted in Hyprland itself or the hy3 plugin.

**Comment by zetaPRIME** [comment]
Seems to still happen if using fade animations.

**Comment by SimonBrandner** [comment]
Damn, forgot to cover that case... @zetaPRIME, could you please open a new issue for this?

**Comment by SimonBrandner** [comment]
@zetaPRIME, hopefully this fixes the issue: https://github.com/outfoxxed/hy3/pull/119
