### ISSUE TITLE
hy3:focustab throws error in 0.40.0

### ISSUE THREAD

**Issue by pokkos** [outfoxxed/hy3#106]
### Description
In the latest hy3 version, hy3:focustab doesn't work anymore. Nothing happens when triggering the dispatcher. But the log file states this error:
```bash
[LOG] Keybind triggered, calling dispatcher (8, , 65289)
[ERR] Listener 100660822953464 threw or timed out and was killed by Watchdog!!! This is bad. what(): Attempted to get group value of a non-group Hy3NodeData
```

when triggering this combination:
```
bind = ALT, TAB, hy3:focustab, r, wrap
```

It doesn't depend on the actual keys, I also tried with different ones. My guess is that is has to do with commit dc5a022 but my C++ unfortunately is not that good to find the issue here.

### Versions
hyprland: 0.40.0 (cba1ade)
hy3: 0.40.0 (584a1b1)

**Comment by outfoxxed** [comment]
Yes that would be the commit. I'll take a look.
The good news is it was probably doing some random undefined behavior before that point.
