### ISSUE TITLE
Update Hyprland URL to new format

### ISSUE THREAD

**Issue by luiswirth** [outfoxxed/hy3#108]
https://github.com/hyprwm/Hyprland/pull/5667 was merged into Hyprland meaning the flake URL was changed from something like:

`inputs.hyprland.url = "github:hyprwm/Hyprland";`
to:
`inputs.hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1";`

hy3 should be updated to reflect this change.
See this other plugin levnikmyskin/hyprland-virtual-desktops#40

**Comment by outfoxxed** [comment]
Yeah I was going to update it at the next breaking change. I've had it set to that before but reverted it for 0.40
