### ISSUE TITLE
i3 resize mode

### ISSUE THREAD

**Issue by tuxx** [outfoxxed/hy3#11]
Would it be possible to implement i3 like resizing? In i3 it works like, enable resizing mode, resize the focussed window with arrow keys, hit escape to exit resizing mode. Not sure if that's in the scope of this project.

**Comment by outfoxxed** [comment]
This can be accomplished with a hyprland submap and the hyprland resize dispatcher.
The current logic backing said resize dispatcher always increases the size of the focused window in the direction you press. If this isn't what you want, please explain in detail how the dispatcher should work.

**Comment by tuxx** [comment]
Seems like i missed that part in the documentation. This suits my needs pretty much, so i will close this issue. Thanks!
