### ISSUE TITLE
Toggle focus between tiled and floating windows

### ISSUE THREAD

**Issue by LRitzdorf** [outfoxxed/hy3#110]
I've just installed hy3, and have noticed a minor discrepancy compared to base Hyprland: the `hy3:movefocus` dispatcher doesn't cycle focus to or from floating windows.

This is actually in line with i3, and is (imo) more intuitive. The key difference is that i3 also provides the `focus mode_toggle` command ([relevant docs](https://i3wm.org/docs/userguide.html#_focusing_moving_containers)), which switches between floating and tiling... "focus domains," for lack of a better phrase. Could hy3 provide something analogous to this?

Somewhat adjacent to #85, except that we're just concerned with making the window active, rather than moving it.

**Comment by outfoxxed** [comment]
Yeah I've been considering that but just haven't gotten around to it yet.

**Comment by outfoxxed** [comment]
Added in 4bc32709c7b8f831e39ec2a7921030c08dbdf500

**Comment by LRitzdorf** [comment]
Nice, thank you!!
