### ISSUE TITLE
Tabs on the tab bar should be clickable

### ISSUE THREAD

**Issue by sin-ack** [outfoxxed/hy3#116]
Hi! Awesome project, works great. Perhaps a rather frivolous request, but on i3, I use my mouse to click on tabs a lot when I have to use my mouse on something (i.e. swapping back-and-forth between two windows to compare something visually). Is this possible with current hy3? If not, would it be possible to add this (maybe as a configuration option)?

**Comment by outfoxxed** [comment]
`bindn = , mouse:272, hy3:focustab, mouse`
