### ISSUE TITLE
Not building on newest Hyprland commit (NixOS)

### ISSUE THREAD

**Issue by RedJ1ve** [outfoxxed/hy3#117]
Hi, just updated my nix flake, and hy3 isn't building following the newest Hyprland commit. It builds just fine if i don't follow the newest commit, but wont load in Hyprland. 

This is the error message when it fails to build:

`error: builder for '/nix/store/08brhjswgkc2gv032iw1ig4fj1gsj1vl-hy3-hl0.40.0.drv' failed with exit code 1;
       last 30 log lines:
       >       |                            ^
       > [2/7] Building CXX object CMakeFiles/hy3.dir/src/main.cpp.o
       > [3/7] Building CXX object CMakeFiles/hy3.dir/src/SelectionHook.cpp.o
       > [4/7] Building CXX object CMakeFiles/hy3.dir/src/dispatchers.cpp.o
       > [5/7] Building CXX object CMakeFiles/hy3.dir/src/Hy3Node.cpp.o
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Node.cpp: In member function 'PHLWINDOW Hy3Node::bringToTop()':
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Node.cpp:212:1: warning: control reaches end of non-void function [-Wreturn-type]
       >   212 | }
       >       | ^
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Node.cpp: In member function 'Hy3Node* Hy3Node::getFocusedNode(bool, bool)':
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Node.cpp:275:1: warning: control reaches end of non-void function [-Wreturn-type]
       >   275 | }
       >       | ^
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Node.cpp: In member function 'bool Hy3Node::isUrgent()':
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Node.cpp:620:1: warning: control reaches end of non-void function [-Wreturn-type]
       >   620 | }
       >       | ^
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Node.cpp: In member function 'void Hy3Node::recalcSizePosRecursive(bool)':
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Node.cpp:381:71: warning: 'constraint' may be used uninitialized [-Wmaybe-uninitialized]
       >   381 |             group.layout != Hy3GroupLayout::Tabbed ? child_count <= 0 ? 0 : constraint / child_count : 0;
       >       |                                                      ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Node.cpp:362:16: note: 'constraint' was declared here
       >   362 |         double constraint;
       >       |                ^~~~~~~~~~
       > [6/7] Building CXX object CMakeFiles/hy3.dir/src/Hy3Layout.cpp.o
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Layout.cpp: In member function 'bool Hy3Layout::shouldRenderSelected(const PHLWINDOW&)':
       > /build/qqv0iazsxs8pdrs9vc75ngq6z371aza3-source/src/Hy3Layout.cpp:1401:1: warning: control reaches end of non-void function [-Wreturn-type]
       >  1401 | }
       >       | ^
       > ninja: build stopped: subcommand failed.`

**Comment by outfoxxed** [comment]
Fixed

**Comment by RedJ1ve** [comment]
Thanks!
