### ISSUE TITLE
Execute the plug -in error in a certain situation

### ISSUE THREAD

**Issue by jack9603301** [outfoxxed/hy3#118]
Execute the plug -in error in a certain situation

exec makegroup tab

[ 5860.037912] Hyprland[788]: segfault at 8 ip 00007f02b0227d74 sp 00007ffcb2f3a1d0 error 4 in hy3.so[7f02b0223000+4d000] likely on CPU 2 (core 2, socket 0)
[ 5860.037955] Code: 2b 04 25 28 00 00 00 75 08 48 89 df e8 c5 d1 ff ff e8 90 c6 ff ff 4c 89 e1 4c 89 ee 48 89 df e8 a2 cb ff ff e9 97 2a 04 00 90 <8b> 04 25 08 00 00 00 0f 0b 48 89 fe 45 31 c9 4c 89 f7 49 89 e8 4c

config

```
bind = $mainMod, z, hy3:makegroup, tab
```

hyprland main branch

Hyprland, built from branch main at commit 4168b8c17b12b90873fab1ca73c2981b53f48bf5 dirty (seat: fix pointer frame events not being sent correctly).
Date: Sun Jun 9 23:23:28 2024
Tag: v0.40.0-180-g4168b8c1, commits: 4786

flags: (if any)

**Comment by outfoxxed** [comment]
Probably fixed in the latest commit.

**Comment by jack9603301** [comment]
@outfoxxed Thank you, I like hyprland, it is more advanced than i3wm in concept, and it does not exclude graphics card users. I like hyprland, but this is my first time trying to use a third-party layout engine other than the built-in support. I hope you, your community and the hyprland you rely on will do better and better.
