### ISSUE TITLE
Update to `0.40.1`

### ISSUE THREAD

**Issue by daniel-hernandez-sony** [outfoxxed/hy3#122]
I am opening this issue to ask for 2 things:
1. Ask to to bump the version to `0.40.1` so that I may use `hy3` with the (currently) latest Hyprland version (The rev for the [commit](https://github.com/hyprwm/Hyprland/commit/9e781040d9067c2711ec2e9f5b47b76ef70762b3) is  `9e781040d9067c2711ec2e9f5b47b76ef70762b3`)
2. Ask what's the process for updating the version number. As far as I can see from a [previous commit of yours](https://github.com/outfoxxed/hy3/commit/5693ea255455c0c35d97353031de80def61f1e15) one has to
    - Update `flake.nix` So that the hyprland input URL points to the correct revision:
    - Update the `hyprpm.toml` with a new item to the list where the first value is the hyprland rev and the second value is something that eludes me (could you shed some light?)
    - Update the `flake.lock`
  
I am happy to open a small PR where I add the proper instructions for doing versioning update PR on a `CONTRIBUTING` section. Of course, this is your repo and I leave it at your discretion.

Thank you for this plugin, it's my daily driver

**Comment by Nyslay** [comment]
Regarding question from point 2: "Update the hyprpm.toml with a new item to the list where the first value is the hyprland rev and the second value is something that eludes me (could you shed some light?)" it looks like 2nd value in this toml is uuid of hy3 commit.
For example https://github.com/outfoxxed/hy3/commit/5693ea255455c0c35d97353031de80def61f1e15 is a commit which bump version, and 2nd value in toml changed in this file is pointing to one commit before this one: https://github.com/outfoxxed/hy3/commit/b6a777d2714628d2cda8843aec73a700ef269899

**Comment by outfoxxed** [comment]
The process is:
1. bump the flake reference to the hyprland release
2. update lockfile
3. add a pin in hyprpm.toml, first is hyprland rev second is hy3 rev.
4. update changelog headers

doing it now
