### ISSUE TITLE
Failed to load the plugin

### ISSUE THREAD

**Issue by Noname672** [outfoxxed/hy3#123]
When installing on nixos like the instruction with the latest hyprland and hy3, I got
```
Failed to load the following plugins:
/nix/store/ffx97m376ildmagwsbrlj94zayrz329f-hy3-hl0.41.1/lib/libhy3.so
```
When I load with hyprctl
```
> hyprctl plugin load /nix/store/ffx97m376ildmagwsbrlj94zayrz329f-hy3-hl0.41.1/lib/libhy3.so
error in loading plugin, last error: Plugin /nix/store/ffx97m376ildmagwsbrlj94zayrz329f-hy3-hl0.41.1/lib/libhy3.so could not be loaded: /nix/store/ffx97m376ildmagwsbrlj94zayrz329f-hy3-hl0.41.1/lib/libhy3.so: undefined symbol: _ZN11IHyprLayout23onWindowCreatedFloatingEN9Hyprutils6Memory14CSharedPointerI7CWindowEE
```

The exact same thing happens when I use the `8c64a4bad710fb18e9b84812bd680a89d1e93661` revision of hyprland, which is found in the flake input of this repo.

**Comment by daniel-hernandez-sony** [comment]
As you can see, the error tells us that hy3 version `0.41.1` could not be loaded. This makes sense given that if you go to the release page for this project, the latest release was `0.41.0`. hy3 is normally a few days behind the latest release of hyprland. So I suggest that you wait until @outfoxxed does a release to match the 0.41.1 version.

**Comment by Noname672** [comment]
Using the revision `8c64a4bad710fb18e9b84812bd680a89d1e93661` of hyprland, which is version 0.41.0 also gives the exact same error
```
> hyprctl plugin load /nix/store/2q1hsyz4hn73smfckky0j52p1fjirqhv-hy3-hl0.41.0/lib/libhy3.so
error in loading plugin, last error: Plugin /nix/store/2q1hsyz4hn73smfckky0j52p1fjirqhv-hy3-hl0.41.0/lib/libhy3.so could not be loaded: /nix/store/2q1hsyz4hn73smfckky0j52p1fjirqhv-hy3-hl0.41.0/lib/libhy3.so: undefined symbol: _ZN11IHyprLayout23onWindowCreatedFloatingEN9Hyprutils6Memory14CSharedPointerI7CWindowEE
```

For the record, this is my input
```
inputs = {
  hyprland = {
    type = "git";
    url = "https://github.com/hyprwm/Hyprland";
    submodules = true;
    rev = "8c64a4bad710fb18e9b84812bd680a89d1e93661";
  };
  hy3 = {
    url = "github:outfoxxed/hy3";
    inputs.hyprland.follows = "hyprland";
  };
}
```

**Comment by outfoxxed** [comment]
[8c64a4bad710fb18e9b84812bd680a89d1e93661](https://github.com/hyprwm/Hyprland/commit/8c64a4bad710fb18e9b84812bd680a89d1e93661) isn't 0.41.0. You're not using the tags on hyprland or hy3.
