### ISSUE TITLE
Building from AUR fails

### ISSUE THREAD

**Issue by the-nexi** [outfoxxed/hy3#13]
Building from AUR fails with the following error on TabGroup.cpp.o ( also adding as a screenshot because log pastes with incorrect padding):

`[ 71%] Building CXX object CMakeFiles/hy3.dir/src/TabGroup.cpp.o
/home/alpha/.cache/paru/clone/hy3-git/src/hy3/src/TabGroup.cpp: In member function ‘void Hy3TabGroup::renderTabBar()’:
/home/alpha/.cache/paru/clone/hy3-git/src/hy3/src/TabGroup.cpp:559:49: error: ‘struct SCurrentRenderData’ has no member named ‘damage’; did you mean ‘pDamage’?
  559 |                     g_pHyprOpenGL->m_RenderData.damage.pixman(),
      |                                                 ^~~~~~
      |                                                 pDamage
make[2]: *** [CMakeFiles/hy3.dir/build.make:132: CMakeFiles/hy3.dir/src/TabGroup.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hy3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`

![изображение](https://github.com/outfoxxed/hy3/assets/49563183/3d9dc987-01e5-4931-80ef-f7bc7a799372)

**Comment by outfoxxed** [comment]
Quoting the readme
> hy3 always tracks the latest (git) version of hyprland. It likely will not work when built against a given stable hyprland release

**Comment by the-nexi** [comment]
Sorry, my bad

thought I'm having git version on my system

Thanks for your time
