### ISSUE TITLE
Font rendering on tabs looks extremely blurry

### ISSUE THREAD

**Issue by BBaoVanC** [outfoxxed/hy3#137]
I couldn't find anyone else having this issue, but for me the tab bar has super blurry text. I tried different fonts (Open Sans, JetBrains Mono) and it didn't fix it.

Please compare the font sharpness to terminal or waybar.

![image](https://github.com/user-attachments/assets/515cc396-268b-43a0-a757-4fa1cfa6c33b)

**Comment by TraceLD** [comment]
I'm also having the same issue with the following text config:
```
plugin {
    hy3 {
        tabs {
            height = 22
            padding = 5
            rounding = 5
            render_text = true
            text_font = SF Pro
            text_height = 10
            text_padding = 5
        }
    }
}
```

**Comment by outfoxxed** [comment]
Just got to this, it appears to be an upstream issue
![image](https://github.com/user-attachments/assets/1ce108f1-3493-4037-bdb6-7adbbca18c39)

**Comment by outfoxxed** [comment]
On further inspection it looks like a pixel boundary error, I'll see if i can fix it here.

**Comment by TraceLD** [comment]
> On further inspection it looks like a pixel boundary error, I'll see if i can fix it here.

Do you know if it has been reported in Hyprland?

**Comment by BBaoVanC** [comment]
It doesn't really seem like it's fixed for me, but if it's an upstream issue then someone should report it to Hyprland. I don't really have time right now to look into it fully and submit an issue upstream right now.

**Comment by outfoxxed** [comment]
> It doesn't really seem like it's fixed for me, but if it's an upstream issue then someone should report it to Hyprland. I don't really have time right now to look into it fully and submit an issue upstream right now.

There may be something additional making your text rendering blurry, but it's probably not related to hy3. The fix above was to make sure text is only ever placed on pixel boundaries, which seemed to help for me.

**Comment by TraceLD** [comment]
The fix has fixed the issue for me as well.
