### ISSUE TITLE
Cannot build on Opensuse Tumbleweed after the last commit with MONITORID

### ISSUE THREAD

**Issue by citysexx** [outfoxxed/hy3#140]
Hello. My issue is that i cannot build hy3 plugin anymore. Here is the compile log:
```bash
citysexx@geeko ~/hy3 (master)> cmake --build build
[ 14%] Building CXX object CMakeFiles/hy3.dir/src/main.cpp.o
In file included from /home/citysexx/hy3/src/globals.hpp:9,
                 from /home/citysexx/hy3/src/main.cpp:7:
/home/citysexx/hy3/src/Hy3Layout.hpp:78:39: error: ‘MONITORID’ does not name a type
   78 |         void recalculateMonitor(const MONITORID& monitor_id) override;
      |                                       ^~~~~~~~~
```
It used to be okay before your last commit (`23682f7`). 
I cloned the repo, made a hard reset to the commit `6af5f60`, (previous one) and could build successfully! 

Could you please look into the build issue?

Platform: OpenSuse TW
Kernel version: 6.10.7-1-default
Hyprland version: 0.42.0 (zypper rpm package latest)
Compilers are latest too.
CPU: Amd Ryzen 7 7730U
GPU: Amd Graphics Integrated

**Comment by outfoxxed** [comment]
You're building unstable hy3 against stable hyprland. Compatibility is only guaranteed for matching hy3 and hyprland versions, with best effort attempts to have both master branches work together.

**Comment by citysexx** [comment]
Thank you! I as I see, I had two options: 
1. Build hyprland from source and build hy3 plugin from latest git commit
2. Install hyprland 0.42 and build hy3 from the commit on version 0.42 (no wonder it works when i reverted commit)

Anyway, thanks for explanation!
