### ISSUE TITLE
Hy3 from nixpkgs fails to load.

### ISSUE THREAD

**Issue by rachitve6h2g** [outfoxxed/hy3#142]
I have a flake based hyprland setup (hyprland package used is also from master, using flake).
Hy3 plugin fails to load in the following home.nix configuration
```nix
wayland.windowManager.hyprland = {
#....
plugins = with pkgs.hyprlandPlugins; [
hy3
];
...
}
```
The error that shows 
```
Failed to load the plugin
/nix/store/XXXX(big_value here)XXX/hy3.0.42.0/libhy3.so
```

Please get the latest hy3 plugin on nixpkgs. Thank you.

**Comment by outfoxxed** [comment]
From the readme:
![image](https://github.com/user-attachments/assets/d7ea31fc-2888-48b4-9b69-9f3670ccb5e0)
