### ISSUE TITLE
hy3:movetoworkspace compatibility with hyprsplit

### ISSUE THREAD

**Issue by BBaoVanC** [outfoxxed/hy3#144]
If I use `hy3:changefocus, raise`, then I can select multiple windows (entire containers) at once. But I can't then move that entire set of windows to a different workspace and instead have to do it manually. This means I also have to manually redo the layout of those windows on the new workspace.

Is there a workaround for this, or can this be added to `hy3:movewindow`?

**Comment by outfoxxed** [comment]
You want `hy3:movetoworkspace`

**Comment by BBaoVanC** [comment]
Ah I see what the problem was, I am also using hyprsplit so my movetoworkspace was overridden by split:movetoworkspacesilent.. Is this something hy3 can add compatibility for, or does it have to be done on hyprsplit's end?

**Comment by outfoxxed** [comment]
This probably requires work on both ends. It depends exactly what hyprsplit does. I assume what happens is hyprsplit just picks a different workspace id to move the window to than hy3 does, in which case having an exposed function to dlsym which hy3 can call would work.

**Comment by outfoxxed** [comment]
This shouldn't be particularly hard to do either. I don't personally have much time at the moment though.

**Comment by outfoxxed** [comment]
Opened https://github.com/shezdy/hyprsplit/issues/32

**Comment by BBaoVanC** [comment]
Awesome, thanks for looking into it! If you don't have time, I also could try making a PR once hyprsplit adds support for that or whatever,

**Comment by outfoxxed** [comment]
If it works the way I think its going to work it should only be a couple lines on both ends to fix it, shouldn't be a big deal.
