### ISSUE TITLE
HEAD version of hy3 ( 4c79361db9c065886c163d1cf873889e1e641e44 ) not compatible with hyprland 0.45.0

### ISSUE THREAD

**Issue by dmayle** [outfoxxed/hy3#153]
[LOG]  [PluginSystem] Plugin hy3 unloaded.
[LOG] Loading plugin /nix/store/xpb8cim0vfrba7h7b1d47115hms2f4c3-hy3-hl0.45.0/lib/libhy3.so which is now present in config
[ERR]  [PluginSystem] Plugin /nix/store/xpb8cim0vfrba7h7b1d47115hms2f4c3-hy3-hl0.45.0/lib/libhy3.so could not be loaded: /nix/store/xpb8cim0vfrba7h7b1d47115hms2f4c3-hy3-hl0.45.0/lib/libhy3.so: undefined symbol: _ZN11IHyprLayout24onWindowCreatedAutoGroupEN9Hyprutils6Memory14CSharedPointerI7CWindowEE
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 13.34µs. Estimated average calc time: 0.04µs.
[LOG] Using config: /home/douglas/.config/hypr/hyprland.conf

**Comment by outfoxxed** [comment]
You need to rebuild the plugin against the latest hyprland version.

**Comment by dmayle** [comment]
In the end, it was user error... I compiled it against the new hyprland,
but accidentally started it with the old hyprland
