### ISSUE TITLE
Crash when moving autotiled windows

### ISSUE THREAD

**Issue by JustSimplyKyle** [outfoxxed/hy3#16]
![image](https://github.com/outfoxxed/hy3/assets/68589851/14ec8bbb-b03b-4c39-b417-e1806a58ed46)
In a scenario like the picture.
if you move the right-down terminal using `movetoworkspace` it will result in a hard crash.
crash report
https://c-v.sh/toeymuller.txt

**Comment by outfoxxed** [comment]
Cannot reproduce on 0.28.0. Master instantly crashes at the moment.
Will investigate again once master builds.

**Comment by Mange** [comment]
Can confirm that the newest `master` works again. Thank you! :heart:
