### ISSUE TITLE
Tab groups not showing up and opening the first window after startup causes plugins not to load

### ISSUE THREAD

**Issue by myamusashi** [outfoxxed/hy3#160]
The color bar is not showing up and causing the plugin to suddenly break (requiring hyprpm reload to restart) when the first window is opened

**Comment by outfoxxed** [comment]
What is "the color bar".

**Comment by myamusashi** [comment]
Sorry i mean the tab bar

https://github.com/user-attachments/assets/ab09c12d-3cbf-4bb7-9dd9-ebd7abb16a13

**Comment by outfoxxed** [comment]
Can you check if it happens before https://github.com/hyprwm/Hyprland/pull/8635 and https://github.com/outfoxxed/hy3/commit/71c5a6fb0524d0bddb73c61d49c1c057d86d518d?

It's somewhat difficult to switch out my hyprland version atm.

**Comment by myamusashi** [comment]
No, it's not

**Comment by Maix0** [comment]
I can confirm that using hyprland at commit 92186898c0ca1b3f72922b72c4af1723f0d9b888 and hy3 at commit c51fefd44ec022a064b25ef39749605ccf1cf9a7 the problem isn't present.
both commit are 1 commit before the PR that changed the color stuff. I have no idea why it should change stuff tho.

**Comment by myamusashi** [comment]
When I load the plugin with `hyprctl plugin load`, I get an error like this
```
[CRITICAL] [02:44:30.558901024]
==========================================================================================
ASSERTION FAILED!

CHyprColor: * is a STUB

at: line 39 in Color.hpp
Assertion failed! See the log in /tmp/hypr/hyprland.log for more info.
[ERR] [02:44:30.559029804] [hookSystem] Hook from plugin 5e8c092925b0 caused a SIGSEGV, queueing for unloading.
```
