### ISSUE TITLE
Hyprland 0.46.2: Hy3 fails to build.

### ISSUE THREAD

**Issue by i-ideamama** [outfoxxed/hy3#170]
Hy3 fails to build on Hyprland version 0.46.2.

Distro : Endeavour OS (Arch)

I looked at previous issues and tried installing "hyprwayland-scanner" and "hyprwayland-scanner-git", both of which did not fix the issue.
Also tried "hyprpm update -f" which did not fix the issue.
I have the following : base-devel, cpio, cmake (which seemed to be the issue for some people)
Tried getting hy3 from AUR but the same error persists.

output for 

> hyprpm add https://github.com/outfoxxed/hy3 -v :

`[v] running version returned: Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.3.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1

flags set:
debug

[v] parsed commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887 at branch  on Thu Dec 19 19:26:47 2024, commits 5566
✔ adding a new plugin repository from https://github.com/outfoxxed/hy3
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] 

→ Cloning https://github.com/outfoxxed/hy3                                                                                                                                                 
✔ cloned                                                                                                                                                                                   
✔ found hyprpm manifest                                                                                                                                                                    
✔ parsed manifest, found 1 plugins:                                                                                                                                                        
→ hy3 by outfoxxed version                                                                                                                                                                 
→ Manifest has 21 pins, checking                                                                                                                                                           
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Verifying headers[v] installed version returned: Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.3.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1

flags set:
debug

[v] parsed commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887 at branch  on Thu Dec 19 19:26:47 2024, commits 5566
✔ Hyprland headers OK                                                                                                                                                                      
→ Building hy3                                                                                                                                                                             
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /run/user/1000/hyprpm/advaith && PKG_CONFIG_PATH="/home/advaith/.local/share/hyprpm/headersRoot/share/pkgconfig" cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.3.0")
-- Checking for modules 'hyprland;pixman-1;libdrm;pango;pangocairo;libinput;wayland-client;xkbcommon'
--   Found hyprland, version 0.46.2
--   Found pixman-1, version 0.44.2
--   Found libdrm, version 2.4.124
--   Found pango, version 1.54.0
--   Found pangocairo, version 1.54.0
--   Found libinput, version 1.27.0
--   Found wayland-client, version 1.23.1
--   Found xkbcommon, version 1.7.0
-- Configuring done (1.0s)
-- Generating done (0.0s)
-- Build files have been written to: /run/user/1000/hyprpm/advaith/build

 -> cd /run/user/1000/hyprpm/advaith && PKG_CONFIG_PATH="/home/advaith/.local/share/hyprpm/headersRoot/share/pkgconfig" cmake --build build
[ 14%] Building CXX object CMakeFiles/hy3.dir/src/main.cpp.o
In file included from /run/user/1000/hyprpm/advaith/src/Hy3Node.hpp:13,
                 from /run/user/1000/hyprpm/advaith/src/Hy3Layout.hpp:32,
                 from /run/user/1000/hyprpm/advaith/src/globals.hpp:9,
                 from /run/user/1000/hyprpm/advaith/src/main.cpp:7:
/run/user/1000/hyprpm/advaith/src/TabGroup.hpp:89:46: error: expected class-name before ‘{’ token
   89 | class Hy3TabPassElement: public IPassElement {
      |                                              ^
/run/user/1000/hyprpm/advaith/src/TabGroup.hpp:93:14: error: ‘void Hy3TabPassElement::draw(const Hyprutils::Math::CRegion&)’ marked ‘override’, but does not override
   93 |         void draw(const CRegion& damage) override;
      |              ^~~~
/run/user/1000/hyprpm/advaith/src/TabGroup.hpp:94:14: error: ‘bool Hy3TabPassElement::needsLiveBlur()’ marked ‘override’, but does not override
   94 |         bool needsLiveBlur() override { return false; }
      |              ^~~~~~~~~~~~~
/run/user/1000/hyprpm/advaith/src/TabGroup.hpp:95:14: error: ‘bool Hy3TabPassElement::needsPrecomputeBlur()’ marked ‘override’, but does not override
   95 |         bool needsPrecomputeBlur() override { return false; }
      |              ^~~~~~~~~~~~~~~~~~~
/run/user/1000/hyprpm/advaith/src/TabGroup.hpp:96:21: error: ‘const char* Hy3TabPassElement::passName()’ marked ‘override’, but does not override
   96 |         const char* passName() override { return "Hy3TabPassElement"; }
      |                     ^~~~~~~~
make[2]: *** [CMakeFiles/hy3.dir/build.make:79: CMakeFiles/hy3.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/hy3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

✖ Plugin hy3 failed to build.                                                                                                                                                              
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first
  Try re-running with -v to see more verbose output.

✔ all plugins built                                                                                                                                                                        
✔ installed repository                                                                                                                                                                     
✔ you can now enable the plugin(s) with hyprpm enable                                                                                                                                      
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!

**Comment by outfoxxed** [comment]
Fixed.
