### ISSUE TITLE
How to wrap tabs

### ISSUE THREAD

**Issue by unaccounted-github** [outfoxxed/hy3#171]
Please delete if this post is not supposed to be here.

I don't know how to enable wrapping when using a tab layout with **_hy3:focustab, wrap_**. As a half-baked workaround I have made a binding to get to the 1st tab (but dunno how to make one to get to the last tab). 

Any tips would be appreciated!

**Comment by outfoxxed** [comment]
You need to specify a direction as well, e.g. `hy3:focustab, r, wrap`
