### ISSUE TITLE
`resizeactive` does not always work

### ISSUE THREAD

**Issue by piotryordanov** [outfoxxed/hy3#19]
So, in my config i have the following:

```
bind = $mainMod SHIFT, s, resizeactive, -80 0
bind = $mainMod SHIFT, w, resizeactive, 80 0
```

If i press the bind with `s` it works, but not with `w`.
I have to switch to the other window for it to work.

**Comment by rehanzo** [comment]
I think these bindings are meant to expand only. If you open three vertical windows, try using the `s` and `w` bindings on the middle one. They should work, expanding the window both ways.

**Comment by outfoxxed** [comment]
Yes, they are currently expand only. shrinking support is planned.

**Comment by outfoxxed** [comment]
Also, closing in favor of #14
