### ISSUE TITLE
`hy3:movefocus` doesn't change monitor

### ISSUE THREAD

**Issue by VAWVAW** [outfoxxed/hy3#2]
When using multiple monitors, moving the focus or a window towards the other monitor doesn't change the monitor/workspace.

### Expected behavior:
Using `hy3:movefocus` or `hy3:movewindow` against the edge of the monitor moves to the workspace on the next monitor like `movefocus` and i3/sway.

### Actual behavior:
`hy3:movefocus` stops at the edge of the monitor.

**Comment by outfoxxed** [comment]
On the roadmap currently, just not my top priority.

**Comment by JustSimplyKyle** [comment]
```bash
#!/bin/bash
GapsOut="$(hyprctl getoption general:gaps_out -j | jaq ".int")"
GapsIn="$(hyprctl getoption general:gaps_in -j | jaq ".int")"
Displacement=$(((GapsOut + GapsIn + GapsOut)/2 + 1))
Monitor="$(hyprctl monitors -j)"
MonitorDisplacementWidth="$(jaq ".[] | select(.focused == true).x" <<< "$Monitor")"
Width="$(jaq ".[] | select(.focused == true).width" <<< "$Monitor")"
RightRoughLocation="$(hyprctl activewindow -j | jaq ".at[0] + .size[0] + $Displacement - $MonitorDisplacementWidth")"
LeftRoughLocation="$(hyprctl activewindow -j | jaq ".at[0] - $Displacement - $MonitorDisplacementWidth")"
if [ "$1" == "right" ] ; then
  if [ "$RightRoughLocation" -ge "$Width" ]; then
    hyprctl dispatch focusmonitor +1
  else
    hyprctl dispatch hy3:movefocus r
  fi
elif [ "$1" == "left" ] ; then
  if [ "$LeftRoughLocation" -le 0 ];then
    hyprctl dispatch focusmonitor -1
  else
    hyprctl dispatch hy3:movefocus l
  fi
fi
```
a... "workaround".

**Comment by Safenein** [comment]
I modified the script so that up and down is also working.
That is a nice workaround, thank you.

```bash
#!/bin/bash
NowWindow="$(hyprctl activewindow -j | jq ".address")"

hyprctl dispatch hy3:movefocus "$1"  # && sleep 0.05
ThenWindow="$(hyprctl activewindow -j | jq ".address")"
if [ "$NowWindow" == "$ThenWindow" ]; then
  hyprctl dispatch movefocus "$1"
fi
```

Deleting the sleep 0.05 is working fine for me. You may put it back if you experience any issues.

```
bind = $mainMod, H, exec, movefocus.sh l
bind = $mainMod, L, exec, movefocus.sh r
bind = $mainMod, K, exec, movefocus.sh u
bind = $mainMod, J, exec, movefocus.sh d
```

**Comment by NadVic17** [comment]
Hi guys, here the same behavior for "movetoworkspace", or at least a ... sloppy solution for a problem that has no real other solution yet. I feel dirty myself for coding this, and not just reading into the C++ Code.

Basically does the same as the code above: if the window was able to move, do nothing. If it wasn't, move it to **ANOTHER** workspace. **Not the correct one. Not on the correct side.** Works best with 2 screens and a low amount of windows on each workspace. This is just a small quick fix.

_**movescreen.sh**_:
```
PREPOS=$(hyprctl activewindow -j | jq ".at")
hyprctl dispatch hy3:movewindow $1
sleep 0.05
POSTPOS=$(hyprctl activewindow -j | jq ".at")

if [[ ! "$PREPOS" == "$POSTPOS" ]]
then
    exit
fi


# position didn't change -> move to next workspace!
ACTIVEWORKSPACE=$(hyprctl activewindow -j | jq ".workspace.id")
for i in $(seq 0 100)
do
    WORKSPACEID=$(hyprctl monitors -j | jq ".[$i].activeWorkspace.id")
    if [[ "$WORKSPACEID" == "null" ]]
    then
        break
    fi

    if [[ "$WORKSPACEID" == "$ACTIVEWORKSPACE" ]]
    then
        continue
    fi

    hyprctl dispatch movetoworkspace "$WORKSPACEID"
    exit
done
```

And in the _**hyprland.conf**_:
```
bind=SUPERSHIFT,H,exec,/home/BLA/config/hypr/movescreen.sh l
bind=SUPERSHIFT,L,exec,/home/BLA/config/hypr/movescreen.sh r
bind=SUPERSHIFT,K,exec,/home/BLA/config/hypr/movescreen.sh u
bind=SUPERSHIFT,J,exec,/home/BLA/config/hypr/movescreen.sh d
```

**Comment by JustSimplyKyle** [comment]
iirc, you can do `+1` in the argument, will try one I got home

**Comment by JustSimplyKyle** [comment]
I was thinking of the dispatcher `movewindow`, and `mon:(+/-)1` as its argument

**Comment by oddlySpecificLama** [comment]
Oh, i didn't know that! This works perfectly as well!
So basically:
`hyprctl dispatch movewindow mon:+1`

Also, i found a small bug as well: if you move a window that was first on the left half of a screen to the top half, the position itself doesn't change. But position and size together should be good enough to pin down if the window actually moved. For this dirty dirty script, i won't care about the edge case.

So to summarize:
```
#!/bin/bash

PREPOS=$(hyprctl activewindow -j | jq ".at")
PRESIZE=$(hyprctl activewindow -j | jq ".size")
hyprctl dispatch hy3:movewindow $1
sleep 0.05
POSTPOS=$(hyprctl activewindow -j | jq ".at")
POSTSIZE=$(hyprctl activewindow -j | jq ".size")

if [[ ! "$PREPOS" == "$POSTPOS" ]] || [[ ! "$PRESIZE" == "$POSTSIZE" ]]
then
    exit
fi

hyprctl dispatch movewindow mon:+1
```

Of course it still doesn't move to the correct side, but that's for later, i suppose.

**Comment by JustSimplyKyle** [comment]
Question: Does Hyprland order the Monitor's ID deterministicly? If so, for a purely horizontal layout, it may be possible to put the order in an array, and move it accordingly to the input(l,r,u,d)

**Comment by oddlySpecificLama** [comment]
I just checked with a 3 monitor setup. Sadly, it does not. At least when i reorder the monitors afterwards, "+1" still goes into the same direction as beforehand.

**Comment by JustSimplyKyle** [comment]
```bash
#!/bin/bash

mapfile -t SortedMonitors <<< "$(hyprctl monitors -j | jq -r 'sort_by(.x) | .[] | .id')"
# SortedMonitors=(2 0 1)
CurrentMonitor="$(hyprctl activeworkspace -j | jq ".monitorID")"
Direction="$1"
SortedMonitorsSize="${#SortedMonitors[@]}"

declare CurrentIndex

# find the index of the current monitor in the sorted monitors array
for index in "${!SortedMonitors[@]}"; do
    if [[ "${SortedMonitors[$index]}" == "$CurrentMonitor" ]]; then
        CurrentIndex="$index"
        break
    fi
done

if [[ $Direction == "r" ]]; then
    ((CurrentIndex++))
elif [[ $Direction == "l" ]]; then
    ((CurrentIndex--))
fi

# Loopback logic
if (( CurrentIndex == SortedMonitorsSize )); then
    CurrentIndex=0
elif (( CurrentIndex < 0 )); then
    CurrentIndex=$((SortedMonitorsSize - 1))
fi

NextMonitorId="${SortedMonitors[$CurrentIndex]}"

hyprctl dispatch movewindow mon:"$NextMonitorId"
```
@oddlySpecificLama , use this with arguments `r` or `l`, can you confirm that would this work?
I only have two monitors, but with my primitive testing, this script shall work with a purely horizontal layout

**Comment by sliedes** [comment]
> I was unhappy with the latency introduced by the movefocus script (switching windows felt slow, even after removing the sleep - timing the script, executing it tooks 50 ms). Turns out hyprctl is rather slow to load, probably due to linking to unnecessarily many dynamic libraries. So here's my hacked version that:

... or this PR for hyprctl to link against much less libraries: https://github.com/hyprwm/Hyprland/pull/7212

**Comment by winneratwin** [comment]
The pr fixes movefocus but doesn't fix movewindow although the actual behavior section in the github issue only lists movefocus so in a sense this issue is solved. But I wouldn't say that the issue is fully solved.
