### ISSUE TITLE
Remove window from tabbed group

### ISSUE THREAD

**Issue by DiXN** [outfoxxed/hy3#26]
In case the last group on a workspace is tabbed, each future window will also be sucked into that tabbed group. Is there a way to remove one window from the tab group in order to create a new group with that window or prevent new windows from getting sucked into the tab group?

**Comment by outfoxxed** [comment]
You can use the `hy3:movewindow` dispatcher to move a group out of a tab. the `visible` modifier ignores any other tabs while moving.
Windows spawn from whichever window is focused. You can focus an entire group at once with `hy3:raisefocus` and ignore tabs while changing focus with `hy3:movefocus`


Uploading recording.mp4…

**Comment by DiXN** [comment]
Thank you, I missed the `hy3:movewindow` dispatcher in combination with `visible`. That is exactly what i was looking for.

**Comment by outfoxxed** [comment]
It was added last week I think
