### ISSUE TITLE
[feat] "Smart borders" or no_gaps_when_only

### ISSUE THREAD

**Issue by A-Cloud-Ninja** [outfoxxed/hy3#3]
Hyprland's `master` layout has a `no_gaps_when_only` which turns off a windows borders when it's the only non-layer window tiled in a workspace, identical to sway's `smart_borders`

`hy3` does not currently seem to support this?

**Comment by outfoxxed** [comment]
Not currently implemented, in the backlog

**Comment by outfoxxed** [comment]
Added in b5df837

**Comment by A-Cloud-Ninja** [comment]
Seems like this only removes gaps, does not hide borders?

**Comment by outfoxxed** [comment]
So you want it to hide borders but not remove the gaps? In my testing it removed the gaps and hid the borders.

**Comment by A-Cloud-Ninja** [comment]
As far as I understand the behavior, and as it was working with the master layout prior, it should:

Remove borders
Remove gaps

If the window is the *only* tiled window in the workspace. The hyprland docs aren't particularly clear on it, I should've listed my desires more succinctly. This is how smart borders/gaps (2 different variables i believe) work in sway/i3, so maybe calling it something separate from master may make more sense.

**Comment by A-Cloud-Ninja** [comment]
Actually, no, i can't even confirm it's working *at all*. Do I need to put plugin config *after* my `general` block?

**Comment by outfoxxed** [comment]
This is all I did. It is below all the other blocks but it shouldn't matter
```
plugin {
  hy3 {
    no_gaps_when_only = true
  }
}
```

**Comment by tg-x** [comment]
seems the issue is that this option only works when the single node is a window, but not when it's a tab group.
they should be treated the same
