### ISSUE TITLE
corrupted tab decorations after shutting down monitor

### ISSUE THREAD

**Issue by andresilva** [outfoxxed/hy3#30]
After shutting down the monitor and then turning it back on, all workspaces will include tab decorations (assuming there was any tabbed group before shutting down the monitor). The decorations go away after switching to the workspace that does include a tabbed group.

How to reproduce:
1. Create a tabbed group on workspace 1
2. Open a window on workspace 2
3. Turn off/on monitor (assuming there is only monitor)
4. Workspace 2 with a single window should now have the same tab decorations as workspace 1

**Comment by outfoxxed** [comment]
Should be fixed by f4f92d19b37666b74950aac64acb8e8354eba65d
