### ISSUE TITLE
Installation help.

### ISSUE THREAD

**Issue by ovidius72** [outfoxxed/hy3#35]
Hi, I've installed this package through AUR for archlinux. I'm using hyprland-git. (AMD video card).
The installation process went fine with no issue.
When i set the layout and the plugin configuration as for the docs I got an error about `invalid dispatch requested: 'hy3:movefocus' does not exists hyprland might not work correctly.`
Is there something I'm missing from the documentation.
Any help would be appreciate. 

Thanks

**Comment by xircon** [comment]
Same problem here.

**Comment by ArbitRandomUser** [comment]
did you load the plugin from hyprland config ?

**Comment by xircon** [comment]
Yes,  I copied from the dots:
```
plugin {
--
  | hy3 {
  | tabs {
  | height = 5
  | padding = 8
  | render_text = false
  | }
  |  
  | autotile {
  | enable = true
  | trigger_width = 800
  | trigger_height = 500
  | }
  | }
  | }
```

**Comment by ovidius72** [comment]
> did you load the plugin from hyprland config ?

yes as for the docs. I've alse set the layout to be hy3. Same error as xircon

**Comment by outfoxxed** [comment]
do you have the `plugin = <path>` line as described on the hyprland wiki?

**Comment by xircon** [comment]
Aaaaah,  will look later, time for work!

**Comment by ovidius72** [comment]
> Adding:
> 
> ```
> plugin = /usr/lib/libhy3
> ```
> 
> Seems to work, but run out of time, work!

That was the problem. It seems to work fine now.

Thanks.
