### ISSUE TITLE
[Bug]Opening a new window after a full-screen window will cause an abnormal display

### ISSUE THREAD

**Issue by DreamMaoMao** [outfoxxed/hy3#39]
hyprland version:0.31.0
hy3:version:0.31.0

Opening a new window after a full-screen window will cause an abnormal display

https://github.com/outfoxxed/hy3/assets/30348075/61d7a7a9-2725-45a1-aad0-f35f49fe245d

**Comment by Mange** [comment]
This happens with multimonitor too. Switching focus to another screen and back again will make the window resize as if it was still tiled and not fullscreen, but the other windows will be invisible.

**Comment by katawful** [comment]
I only seem experience this if I've tabbed a group and switch from a secondary monitor to the monitor with the fullscreen application

**Comment by outfoxxed** [comment]
This was a real issue btw, I had it myself.
