### ISSUE TITLE
Unable to have a bold font in title

### ISSUE THREAD

**Issue by aacebedo** [outfoxxed/hy3#40]
Hello,

I am currently evaluating hyprland and hy3 (version 0.31.0) to switch from Sway on NixOS.
I installed the nerdfonts package.
The plugin is working pretty well but I noticed something I am unable to do.
I would like to use a bold font in the tabs title. Changed the "text_font" to "NotoSansNF Bold" as described in the Pango Documentation (https://docs.gtk.org/Pango/type_func.FontDescription.from_string.html).
However, it does not work. I also tried "Sans Bold" to rule out a problem on the Family but to no extend.

What am I missing here?

**Comment by outfoxxed** [comment]
I've never tested this. Do you know if it works with hyprland's normal group bars? I think i copied the text rendering from there.

**Comment by aacebedo** [comment]
Don't think hyprland support setting a font in the group bar at the moment.
This PR is adding the support of it but it is not yet merged:
https://github.com/hyprwm/Hyprland/pull/3197

**Comment by aacebedo** [comment]
The problem was I made an error in the pango name of the font.
