### ISSUE TITLE
hy3 on AUR compatibility with hyprland-nvidia

### ISSUE THREAD

**Issue by wisheth** [outfoxxed/hy3#45]
Installing hy3 with AUR when hyprland-nvidia is installed shows hyprland and hyprland-nvidia being in conflict. It is possible to remedy this without uninstalling hyprland-nvidia, or am I forced to reconfigure my setup?

**Comment by outfoxxed** [comment]
hyprland in the main arch repos is a version behind hyprland-nvidia in the aur (which is a version behind hyprland everywhere else) so you'll have to build manually from the tag if you want 0.31.x.

**Comment by Chr1s70ph** [comment]
This issue can be closed. `hyprland-nvidia` is no longer a thing: https://github.com/hyprwm/Hyprland/pull/3957
