### ISSUE TITLE
Wezterm extremely slow to open with hy3 layout active

### ISSUE THREAD

**Issue by ndom91** [outfoxxed/hy3#49]
Hey team, great plugin here! Finally have some of the group features back that I loved from i3!

My only complaint so far is that my terminal of choice, `wezterm`, takes extremely long to open on a new workspace. So oddly, once I have wezterm open once on a workspace, it'll open almost immediately just like any other window. However, if there are no other wezterm windows open yet on the particular workspace, then it takes up to 1 minute for the window to open. 

Anything I can do to help debug here? I do not see this behaviour with other terminal emulators like Alacritty. 

I'm running `hyprland-git` and `hy3-git` from the AUR with the latest builds as of today (07.12.23 ~19:19 UTC).

**Comment by Mange** [comment]
Just adding my two cents here; I do *not* have this issue and I'm also using Wezterm and Hyprland + hy3.


```
> hyprctl version | head -n1
Hyprland, built from branch  at commit 6e8b9ef7d8aa53247d5122b6641b9afa0df798df  ().
```

I have disabled Wayland in Wezterm since wez/wezterm#4483.

```
grep -C2 wayland ~/.config/wezterm/wezterm.lua
  -- Disabled until Wayland support can be remade to work in Hyprland.
  -- https://github.com/wez/wezterm/issues/4483
  enable_wayland = false,
  audible_bell = "Disabled", -- Disabled on Wayland, not on X11
```

**Comment by ndom91** [comment]
@Mange thanks for the quick response, I'll do some more debugging on my end then 👍

**Comment by outfoxxed** [comment]
There is an almost zero percent chance this is related to hy3 and not hyprland itself. If you can isolate the issue to specifically hy3 please reopen it.
