### ISSUE TITLE
Can't install using hyprpm

### ISSUE THREAD

**Issue by Crandel** [outfoxxed/hy3#59]
I have installed Hyprland yesterday on my Arch Linux machine after using Swaywm for last two years. And I'm missing tabbed layout from it in Hyprland. I tried to install `hy3` using `hyprpm` as was explained in README. 

System: Arch Linux
Hyprland: 0.34.0-1

```sh
$ hyprpm add https://github.com/outfoxxed/hy3
✔ adding a new plugin repository from https://github.com/outfoxxed/hy3
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] y

 → Cloning https://github.com/outfoxxed/hy3
✔ cloned
✔ found hyprpm manifest
✔ parsed manifest, found 1 plugins:
 → hy3 by outfoxxed version
✔ Hyprland headers OK
 → Building hy3
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)
✖ Plugin hy3 failed to build.
```

**Comment by xandayn** [comment]
I also had issues installing this, my solution was to manually install CMake before adding the plugin with hyprpm, It is not installed as part of the "base-devel" package on Arch, but is required to build this project.

**Comment by Crandel** [comment]
@xandayn After installing cmake I can install `hy3` plugin. But after reboot I got error about `hy3:movefocus` dispatcher.

How exactly enable this plugin before binds will be loaded? My current config is:

```conf
exec-once = hyprpm reload -n

plugin {
    hy3 {
        tab_first_window = true
        tabs {
            ...
        }
        ...
    }
}

general {
    ...
    layout = hy3
    ...
}

bind = $mMod, right, hy3:movefocus, r
bind = $mMod, left,  hy3:movefocus, l
bind = $mMod, up,    hy3:movefocus, u
bind = $mMod, down,  hy3:movefocus, d

```

**Comment by xandayn** [comment]
> @xandayn After installing cmake I can install `hy3` plugin. But after reboot I got error about `hy3:movefocus` dispatcher.
> 
> How exactly enable this plugin before binds will be loaded? My current config is:
> 
> ```
> exec-once = hyprpm reload -n
> 
> plugin {
>     hy3 {
>         tab_first_window = true
>         tabs {
>             ...
>         }
>         ...
>     }
> }
> 
> general {
>     ...
>     layout = hy3
>     ...
> }
> 
> bind = $mMod, right, hy3:movefocus, r
> bind = $mMod, left,  hy3:movefocus, l
> bind = $mMod, up,    hy3:movefocus, u
> bind = $mMod, down,  hy3:movefocus, d
> ```

I actually also have this issue, but am unsure if this is actually an issue with hy3 or hyprpm, as a stop-gap while I tried to figure it out I just setup a keybind for hyprpm reload and I hit it after login which is good enough for me. You might want to open a new issue for it though, I don't have the time currently to look into it.
