### ISSUE TITLE
no_gaps_when_only improperly handled on '2'

### ISSUE THREAD

**Issue by Midou36O** [outfoxxed/hy3#61]
The [Official Hyprland Documentation](https://wiki.hyprland.org/Configuring/Master-Layout/#config) Indicate multiple options to choose from.

![image](https://github.com/outfoxxed/hy3/assets/45198486/595cc2c7-bd61-439a-aa35-0afdff5397c5)
hy3 replicates the same feature, unfortunately it only seems to be taking the value 0 or 1 (boolean), not 2.

**Comment by tg-x** [comment]
see https://github.com/outfoxxed/hy3/issues/3#issuecomment-1997063298
