### ISSUE TITLE
Wayland `activate` calls to focus non-visible grouped windows doesn't work

### ISSUE THREAD

**Issue by JakeStanger** [outfoxxed/hy3#7]
Appreciate that's a long title. 

**Current behaviour**
In effect, trying to activate (focus) a window that is part of a tabbed group, but not the currently active group tab, currently does nothing.

**Expected behaviour**
Focusing a window should cause it to become the active group tab, and bring it to focus.

**Repro steps**
- Place two or more windows in a hy3 tabbed group
- Attempt to focus a non-active window in the group (ie via a bar's launcher module)
- Observe nothing happening

---

Thanks for the plugin btw, this is the only real problem I've noticed and it's so far been a great experience.

**Comment by outfoxxed** [comment]
If this is what you're referring to, its intentional:
https://github.com/outfoxxed/hy3/assets/83010835/82f7dc67-9156-487c-827e-252e34e0dafe
Though I could add an option to focus the window instead of just marking it.

If not I'll need more information (what program, how are you activating it)

**Comment by JakeStanger** [comment]
Being able to auto-focus urgent windows would be cool, but that's not the issue I'm experiencing. I've attached a short screen recording that hopefully demos it a bit better:

[2023-07-14 22-14-47.webm](https://github.com/outfoxxed/hy3/assets/5057870

In this case, I've got a group with Chrome and Audacity (programs make no difference, just two random things to hand). Chrome is the 'active' group window, which means I cannot focus Audacity from the bar. The demo shows my own Ironbar, but the same thing happens with Waybar. This occurs irrespective of the currently focused workspace. 

I have also found in the Hyprland log that there seems to be some issue fetching the window:

```
[LOG] Keybind triggered, calling dispatcher (0, mouse:272, 0)
[LOG] update decos for 0x55d4b79cde80 - selected: 0
[LOG] Switched windows to (nil)
```

With Sway and vanilla Hyprland's groups, this scenario does bring Audacity to focus.

Both bars use the `wlr_foreign_toplevel_management` , calling `.activate()` on a toplevel handle:

/001c21b6-6c79-4f99-9ca0-10da2846f74b)
Waybar: https://github.com/Alexays/Waybar/blob/2211a798408adce99679c28bb25dc772da416b1d/src/modules/wlr/taskbar.cpp#L676

Ironbar: https://github.com/JakeStanger/ironbar/blob/2f8443f349d48ecf93676560013b268029a1e95b/src/clients/wayland/wlr_foreign_toplevel/handle.rs#L35

**Comment by outfoxxed** [comment]
Do you have `misc:focus_on_activate` on?

**Comment by JakeStanger** [comment]
I did not previously. I have just tried enabling it, and there seems to be no change in behaviour. I've not seen any evidence that windows are getting marked as urgent when activating them either.

wlroots/wayland don't have a concept of urgency, so that's something Hyprland is bringing into the mix. Unfortunately my knowledge only extends as far as the wlr_foreign_toplevel protocol, but I know that tracks activation via a handle's state.

**Comment by outfoxxed** [comment]
Does this look about right?
https://github.com/hyprwm/Hyprland/blob/7f47655f60be2c54dfa0e1758cbff20ab38217fc/src/Window.cpp#L236
I'll have to make a PR to expose an event if it is.

**Comment by JakeStanger** [comment]
Yeah, that certainly looks like it to me

**Comment by JakeStanger** [comment]
I've just tried the fix and it appears to be hard-crashing Hyprland as soon as I try to activate any window (grouped or not) unfortunately.

When I tried to focus a grouped non-focused window I got an error log with the following in:

```
[LOG] update decos for 0x564450087180 - selected: 0
[LOG] Switched windows to (nil)
[LOG] Move CTor type matches? 1 is group? 1
[LOG] Move CTor type matches? 1 is group? 0
[LOG] opened new window 0x56444c35a690(node: 0x564448a66200) on window (nil) in 0x564448ba3020
[LOG] update decos for 0x56444c35a690 - selected: 0
```

In all other scenarios, Hyprland has not produced a log.

**Comment by outfoxxed** [comment]
Make sure you recompile hy3 against the latest hyprland, and if it persists then send the crash report.

**Comment by JakeStanger** [comment]
```
λ pacman -Q hyprland
hyprland-nvidia 0.27.2-1
```
I've had similar results with the latest `-git` package (nvidia and non-nvidia).

These two are from today. They happened pretty soon after logging in, and weren't triggered by the bar activating a window. I'm not sure what I've done but activating the plugin seems to crash almost immediately now. 

[hyprlandCrashReport1166.txt](https://github.com/outfoxxed/hy3/files/12136730/hyprlandCrashReport1166.txt)
[hyprlandCrashReport1188.txt](https://github.com/outfoxxed/hy3/files/12136731/hyprlandCrashReport1188.txt)

This is from yesterday, and was triggered by activating a bar from the window. It's what the snippet from yesterday is from:

[hyprlandCrashReport27908.txt](https://github.com/outfoxxed/hy3/files/12136732/hyprlandCrashReport27908.txt)

**Comment by outfoxxed** [comment]
By latest hyprland I mean `-git`. Make sure your headers match the hyprland version (rm `/usr/include/hyprland` and `~/.local/include/hyprland`. (This has come up repeatedly)

Can you get a snippet of the backtrace in gdb when using the bar, with debug builds of hyprland and hy3? That should show line numbers.

**Comment by outfoxxed** [comment]
Is this still an issue @JakeStanger

**Comment by JakeStanger** [comment]
Ok! It seems part of the problem was indeed headers - the hyprland-nvidia packages incorrectly install them, meaning hy3 was never successfully (re)building. I've fixed that and can finally confirm the issue is resolved, thanks!

**Comment by andresilva** [comment]
Not sure if there was a regression but this doesn't seem to be working for me on 1376a4f3d02fc17987c18dea1814a7aa90bf92c3. If I try with `hyprctl dispatch focuswindow pid:1337` to focus a tabbed window it doesn't work.

**Comment by outfoxxed** [comment]
@andresilva this issue is referring to focusing the window via the `wlr_foreign_toplevel_management` protocol, hyprctl likely never worked for this. Please open an issue for it and I'll fix it.
