### ISSUE TITLE
Build failure after Hyprland@b2c3440

### ISSUE THREAD

**Issue by SoulHarsh007** [outfoxxed/hy3#81]
:wave: It seems like commit https://github.com/hyprwm/Hyprland/commit/b2c34404777ea0850f90f4c38f64484f03599d14 from Hyprland would require changes in hy3.

Build log: https://paste.soulharsh007.dev/p/e360882.log

**Comment by MitchMG2** [comment]
If you're on Arch and do not want to manually build Hyprland against a specific commit: the latest official repo package is from before the offending commit. I installed that and rebuilt hyprpm against it and got hy3 working again for now.

**Comment by outfoxxed** [comment]
Fixed in a392bfd
