### ISSUE TITLE
Is this possible to put all windows under a common tab with one command ?

### ISSUE THREAD

**Issue by StitiFatah** [outfoxxed/hy3#83]
Hi, 

On i3 doing a raw `bindsym $mod+w layout tabbed` put all the already tiled windows under a tab, here `bind = $mod, w, hy3:makegroup, tab ` only put the current one under a tab and one would need to push the other ones under this tab to get i3's result. 

It's not problematic if one just want tabbed windows from the start but I often open multiple vertically tiled window and then tab them when it's too clustered. I now often see myself use the fullscreen instead of tabs in that situation since it's more straightforward, but it's obviously less convenient than tabs. 

I've tried the options listed in the docs and also the author's own config but can't seem to fins anything. Am i missing something or is it just not possible with the current implementation and would at least require to script it ?

Thanks.

**Comment by outfoxxed** [comment]
`hy3:changegroup tab`

**Comment by StitiFatah** [comment]
My bad I could have sworn I tried and it didn't work, thanks
