### ISSUE TITLE
How to toggle split?

### ISSUE THREAD

**Issue by emanueljg** [outfoxxed/hy3#86]
On i3, I had a setup where I'd toggle horizontal/vertical split on `$mod+v`, so pressing the chord multiple times would make the split cycle between vertical to horizontal to vertical and so on. How do I replicate this behavior in hy3?

**Comment by victorz** [comment]
It's this, from the README:

- `hy3:changegroup, <h | v | tab | untab | toggletab | opposite>` - change the group the node belongs to, to a different layout
    - `untab` will untab the group if it was previously tabbed
    - `toggletab` will untab if group is tabbed, and tab if group is untabbed
    - **`opposite`** will toggle between horizontal and vertical layouts if the group is not tabbed.

You then want: `bind = $mod, v, hy3:changegroup, opposite`.

**Comment by emanueljg** [comment]
Thanks!
