### ISSUE TITLE
hyprland/src/Window.hpp: No such file or directory

### ISSUE THREAD

**Issue by polnio** [outfoxxed/hy3#89]
Hi!
I'm using the main branch of hyprland, and when I try to compile hy3 I have this error:

> In file included from /tmp/hyprpm/update/src/Hy3Layout.hpp:25,
                 from /tmp/hyprpm/update/src/globals.hpp:8,
                 from /tmp/hyprpm/update/src/main.cpp:7:
/tmp/hyprpm/update/src/Hy3Node.hpp:9:10: fatal error: hyprland/src/Window.hpp: No such file or directory
    9 | #include <hyprland/src/Window.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/hy3.dir/build.make:76: CMakeFiles/hy3.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hy3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I checked hyprland's repository and yesterday they moved the file `src/Window.hpp` to `src/desktop/Window.hpp` (https://github.com/hyprwm/Hyprland/commit/8593c45be3cfe8055d13315051d88588f848ad39), so the file included in `Hy3Node.hpp` doesn't exist anymore

**Comment by talpadk** [comment]
I think this issue should be closed as it was fixed in:

commit aa9aae294e987ac60779b6396d485517fd6cc4b2
Author: eriedaberrie <eriedaberrie@gmail.com>
Date:   Wed Mar 20 21:47:04 2024 -0700

    Fix compile after hyprland header location change
