### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ansdim1** [outfoxxed/hy3#9]
hyprland version **0.27.2**

yay -S hy3-git
AUR Explicit (1): hy3-git-r124.7c29490-2
:: (1/1) Downloaded PKGBUILD: hy3-git
  1 hy3-git                          (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> All
:: Deleting (1/1): /home/d/.cache/yay/hy3-git
HEAD is now at 6ecf820 Fix missing build dependencies
  1 hy3-git                          (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> None
==> Making package: hy3-git r124.7c29490-2 (Вт 25 июл 2023 00:30:29)
==> Retrieving sources...
  -> Cloning hy3 git repo...
Cloning into bare repository '/home/d/.cache/yay/hy3-git/hy3'...
remote: Enumerating objects: 779, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 779 (delta 50), reused 54 (delta 37), pack-reused 705
Receiving objects: 100% (779/779), 204.33 KiB | 1.36 MiB/s, done.
Resolving deltas: 100% (554/554), done.
==> Validating source files with sha256sums...
    hy3 ... Skipped
:: (1/1) Parsing SRCINFO: hy3-git
==> Making package: hy3-git r124.7c29490-2 (Вт 25 июл 2023 00:30:31)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating hy3 git repo...
==> Validating source files with sha256sums...
    hy3 ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of hy3 git repo...
Cloning into 'hy3'...
done.
==> Starting pkgver()...
==> Updated version: hy3-git r156.3fbaa4a-1
==> Sources are ready.
==> Making package: hy3-git r156.3fbaa4a-1 (Вт 25 июл 2023 00:30:33)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
-- The C compiler identification is GNU 13.1.1
-- The CXX compiler identification is GNU 13.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1")
-- Checking for modules 'hyprland;pixman-1;libdrm;pango;pangocairo'
--   Found hyprland, version 0.27.2
--   Found pixman-1, version 0.42.2
--   Found libdrm, version 2.4.115
--   Found pango, version 1.50.14
--   Found pangocairo, version 1.50.14
-- Configuring done (1.5s)
-- Generating done (0.0s)
-- Build files have been written to: /home/d/.cache/yay/hy3-git/src/build
[ 28%] Building CXX object CMakeFiles/hy3.dir/src/main.cpp.o
[ 28%] Building CXX object CMakeFiles/hy3.dir/src/dispatchers.cpp.o
[ 42%] Building CXX object CMakeFiles/hy3.dir/src/Hy3Layout.cpp.o
[ 57%] Building CXX object CMakeFiles/hy3.dir/src/Hy3Node.cpp.o
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Layout.cpp: In member function 'virtual CWindow* Hy3Layout::getNextWindowCandidate(CWindow*)':
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Layout.cpp:651:1: warning: control reaches end of non-void function [-Wreturn-type]
  651 | }
      | ^
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Layout.cpp: In member function 'void Hy3Layout::setNodeSwallow(int, SetSwallowOption)':
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Layout.cpp:1000:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1000 |         case SetSwallowOption::NoSwallow: *containment = false;
      |                                           ~~~~~~~~~~~~~^~~~~~~
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Layout.cpp:1001:9: note: here
 1001 |         case SetSwallowOption::Swallow: *containment = true;
      |         ^~~~
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Layout.cpp:1001:54: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1001 |         case SetSwallowOption::Swallow: *containment = true;
      |                                         ~~~~~~~~~~~~~^~~~~~
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Layout.cpp:1002:9: note: here
 1002 |         case SetSwallowOption::Toggle: *containment = !*containment;
      |         ^~~~
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Layout.cpp: In member function 'bool Hy3Layout::shouldRenderSelected(CWindow*)':
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Layout.cpp:1040:1: warning: control reaches end of non-void function [-Wreturn-type]
 1040 | }
      | ^
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Node.cpp: In member function 'bool Hy3Node::focusWindow()':
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Node.cpp:152:1: warning: control reaches end of non-void function [-Wreturn-type]
  152 | }
      | ^
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Node.cpp: In member function 'Hy3Node* Hy3Node::getFocusedNode()':
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Node.cpp:204:1: warning: control reaches end of non-void function [-Wreturn-type]
  204 | }
      | ^
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Node.cpp: In member function 'bool Hy3Node::isUrgent()':
/home/d/.cache/yay/hy3-git/src/hy3/src/Hy3Node.cpp:461:1: warning: control reaches end of non-void function [-Wreturn-type]
  461 | }
      | ^
[ 71%] Building CXX object CMakeFiles/hy3.dir/src/TabGroup.cpp.o
[ 85%] Building CXX object CMakeFiles/hy3.dir/src/SelectionHook.cpp.o
/home/d/.cache/yay/hy3-git/src/hy3/src/TabGroup.cpp: In member function 'void Hy3TabGroup::renderTabBar()':
/home/d/.cache/yay/hy3-git/src/hy3/src/TabGroup.cpp:559:49: error: 'struct SCurrentRenderData' has no member named 'damage'; did you mean 'pDamage'?
  559 |                     g_pHyprOpenGL->m_RenderData.damage.pixman(),
      |                                                 ^~~~~~
      |                                                 pDamage
make[2]: *** [CMakeFiles/hy3.dir/build.make:132: CMakeFiles/hy3.dir/src/TabGroup.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hy3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hy3-git-exit status 4
removing untracked AUR files from cache...
:: Cleaning (1/1): /home/d/.cache/yay/hy3-git
 -> Failed to install the following packages. Manual intervention is required:
hy3-git - exit status 4

**Comment by outfoxxed** [comment]
hy3 is developed against hyprland-git. use hyprland-git or use a version of hy3 with a version near 0.27 in the lockfile.
