### ISSUE TITLE
hy3:movewindow does not work and (version 0.37.1)

### ISSUE THREAD

**Issue by daniel-hernandez-sony** [outfoxxed/hy3#90]
Thank you for your work, it is my daily driver and I love it.

I want to be able to resize a window (ideally floating ones too) using my mouse. In my config I have:

```
bindm = $mainMod, mouse:272, hy3:movewindow
bindm = $mainMod, mouse:273, resizeactive
```

However, I can't seem to move either non-floating windows (resizing with respect to other windows) or floating windows. These are my only mouse bindings (`bindm`). I do **use a trackpad and not a mouse**, just in case that's different.

- Commit: release 0.37.1
- journalctl shows no Hyprland errors
- No crashes

Do let me know what other info I can provide to help, I understand I am not giving a lot of info.

**Comment by oddlySpecificLama** [comment]
I just checked and had basically the same errors. However, just using the usual `movewindow` command (without hy3) still works for me. Either way, i wouldn't have expected hy3 to change that functionality either way. I don't see any benefits in hy3 modifying my mouse-related activities compared to the default Hyprland behavior, as i only want hy3 to change the tiling order and give me my expected i3 behavior (as i felt like Hyprland lacks this tiling either way, as i can't do everything with my keyboard on default Hyprland-settings).

So maybe it's just me, but the usual `movewindow` gives me my expected experience.

**Comment by daniel-hernandez-sony** [comment]
I agree with you wholeheartedly. 

Changing it to the default `movewindow` (no `hy3:` prefix) also fixed it for me. Thanks man!
